dist: xenial
language: php

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3

env:
  - WP_VERSION=latest

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist"

install:
  - composer install --prefer-dist --no-interaction --no-suggest
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - | # Run PHPUnit
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test:unit -- --debug
      WP_MULTISITE=1 composer test:unit
    fi
